In [2]:
import pandas as pd

## Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [45]:
movies = pd.read_csv('ratings.csv').merge(pd.read_csv('movies.csv'), on='movieId')
movies.title[movies.rating == 5.0].value_counts()

Shawshank Redemption, The (1994)             153
Pulp Fiction (1994)                          123
Forrest Gump (1994)                          116
Matrix, The (1999)                           109
Star Wars: Episode IV - A New Hope (1977)    104
                                            ...
Devil in a Blue Dress (1995)                   1
Bad News Bears, The (1976)                     1
Moonlight                                      1
48 Hrs. (1982)                                 1
1408 (2007)                                    1
Name: title, Length: 2954, dtype: int64

## Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [6]:
power = pd.read_csv('power.csv')
power.head()

   country    year  quantity  category
0  Austria  1996.0       5.0       1.0
1  Austria  1995.0      17.0       1.0
2  Belgium  2014.0       0.0       1.0
3  Belgium  2013.0       0.0       1.0
4  Belgium  2012.0      35.0       1.0

In [25]:
country = ['Lithuania', 'Latvia', 'Estonia']
power[(power.category.isin([4,12,21])) & (power.year >= 2005) & (power.year <= 2010) & (power.country.isin(country)) & (power.quantity >= 0)].sum()['quantity']

country     EstoniaEstoniaEstoniaEstoniaLithuaniaLithuania...
year                                                   819091
quantity                                               240580
category                                                 6678
dtype: object

## Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [48]:
pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8', skiprowslist)[1]

    Unnamed: 0              Рубль  ...  Абсолютное значение     Время
0          NaN            GBP/RUB  ...                15699  21:26:00
1          NaN            EUR/RUB  ...                11620  21:26:00
2          NaN            USD/RUB  ...                07550  21:26:00
3          NaN            JPY/RUB  ...                00077  21:26:00
4          NaN            CNY/RUB  ...                00991  21:26:00
5          NaN            CHF/RUB  ...                10707  21:26:00
6          NaN               Евро  ...  Абсолютное значение     Время
7          NaN            EUR/USD  ...                00034  21:26:00
8          NaN            EUR/GBP  ...               -00023  21:26:00
9          NaN            EUR/JPY  ...                03850  21:26:00
10         NaN            EUR/CHF  ...                00006  21:26:00
11         NaN         Доллар США  ...  Абсолютное значение     Время
12         NaN            USD/EUR  ...               -00026  21:26:00
13         NaN            USD/GBP  ...               -00044  21:26:00
14         NaN            USD/JPY  ...               -00435  21:26:00
15         NaN            USD/CHF  ...               -00026  21:26:00
16         NaN      Японская иена  ...  Абсолютное значение     Время
17         NaN    JPY/EUR (100:1)  ...                00000  21:26:00
18         NaN            JPY/GBP  ...                00000  21:26:00
19         NaN            JPY/USD  ...                00000  21:26:00
20         NaN    JPY/CHF (100:1)  ...                00000  21:26:00
21         NaN    Фунт стерлингов  ...  Абсолютное значение     Время
22         NaN            GBP/USD  ...                00077  21:26:00
23         NaN            GBP/JPY  ...                07190  21:26:00
24         NaN            GBP/EUR  ...                00030  21:25:00
25         NaN            GBP/CHF  ...                00039  21:26:00
26         NaN  Швейцарский франк  ...  Абсолютное значение     Время
27         NaN            GBP/CHF  ...                00039  21:26:00
28         NaN            EUR/CHF  ...                00006  21:26:00
29         NaN    JPY/CHF (100:1)  ...                00000  21:26:00
30         NaN            USD/CHF  ...               -00026  21:26:00
31         NaN  Украинская гривна  ...  Абсолютное значение     Время
32         NaN            EUR/UAH  ...                01622  21:26:00
33         NaN            USD/UAH  ...                00530  21:25:00
34         NaN            CHF/UAH  ...                01415  21:26:00
35         NaN            GBP/UAH  ...                02739  21:26:00

[36 rows x 8 columns]